#!/bin/bash

set -e -u -o pipefail -o noclobber
shopt -s shift_verbose

declare -r HASH="$1"; shift
declare -r JOB="$1";    shift
declare -r HOST="$1";   shift

if ! [[ $HASH =~ ^[0-9a-f]{40}$ ]]; then
    echo "Invalid commit hash: $HASH" >&2
    exit 1
fi

if ! [[ $JOB =~ ^[0-9]+$ ]]; then
    echo "Invalid job number: $JOB" >&2
    exit 1
fi

if ! [[ $HOST =~ ^[a-z0-9_-]+$ ]]; then
    echo "Invalid host name: $HOST" >&2
    exit 1
fi

declare -r JOB_SFX=`printf 'job/%u/%02u' $((JOB/100)) $((JOB%100))`
declare -r SFX="commit/${HASH:0:2}/${HASH:2}"
declare -r JOB_DIR="/srv/ci/logs/$JOB_SFX"
declare -r DIR="/srv/ci/logs/$SFX"
declare -r JOB_LINK="../../../$JOB_SFX"
declare -r HOST_DIR="$JOB_DIR/$HOST"

mkdir -p "$HOST_DIR"
mkdir -p "$DIR"
ln -snf "$JOB_LINK" "$DIR/$JOB"
tar xzmC "$HOST_DIR"
